- title: Nanopore Sequencing & Data Analysis
  subtitle: Learn about nanopore sequecning and data analysis by performing your own 16S sequecning experiement!
  description:
  month: September
  day: 19
  year: 2019
  duration: 1
  institute: University of Sheffield
  city: Sheffield
  location: E13 Dainton Building
  link: http://sbc.shef.ac.uk/training/nanopore-sequencing-2019-09-19/

